# TP n°2

### Félix Ladislas & Maxime Lenfant

Date de la séance : 28/09/2023

___

In [300]:
import numpy as np

___
## Préliminaires

In [301]:
L1 = np.array([1,2,3,4]) ; L2 = L1
L1[1] = 0 ; print(L2)

[1 0 3 4]


On crée un tableau *L1*, puis on déclare un second tableau *L2* égal au premier. Pour finir, on change la deuxième valeur de *L1* et on affiche *L2*. On remarque que le changement est aussi effectif sur le second tableau *L2*.

In [302]:
M1 = [[0]*4]*4 ; print(M1)
M1[1][2] = 5 ; print(M1)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 0, 5, 0], [0, 0, 5, 0], [0, 0, 5, 0], [0, 0, 5, 0]]


On remarque que quelque soit la valeur dans le premier chrochet de la seconde ligne, chaque élément du tableau *M1* change de manière identique.

In [303]:
M1 = np.array([[0]*4]*4)
M1[1][2] = 5 ; print(M1)

[[0 0 0 0]
 [0 0 5 0]
 [0 0 0 0]
 [0 0 0 0]]


Ici, grâce à la déclarationi et initialisation par *numpy*, le changement se fait bien dans un seul élément de *M1*.

In [304]:
A = np.array([[1,2,3],[1,4,9],[1,8,27]])
AA = A ; AA[1,1] = -2 ; A

array([[ 1,  2,  3],
       [ 1, -2,  9],
       [ 1,  8, 27]])

De manière similaire à la première question, le changement effectué sur le tableau *AA* s'effectue aussi sur le tableau *A* dont il est l'origine.

In [305]:
A = np.array([[1,2,3],[1,4,9],[1,8,27]])
AA = A.copy() ; AA[1,1] = -2 ; A

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

Ici, la fonction *copy()* permet de copier un tableau. Un changement sur l'un n'affecte plus l'autre.

___

# Algorithme

In [306]:
def SousLigne(M:list,L1:int,L2:int, f:int):
    # Soustrait la ligne L1 à la ligne L2 de la matrice M :
    # (L2 = L2 - f * L1)

    for i in range (0,len(M[L2])):
        M[L2][i] = M[L2][i] - (f * M[L1][i])

def EchangeLigne(M:list,L1:int,L2:int):
    # Echange L1 et L2 dans le tableau M

    M[L1], M[L2] = M[L2].copy(), M[L1].copy()

def MatriceAugmente(A:list, B:list)->list:
    # retourne la matrice augmentée A|B

    C = np.zeros([len(A), len(A[0]) + len(B[0])], int)
    
    for i in range (0, len(A)):
        for j in range (0, len(C[0])):
            if (j < len(A[0])):
                C[i][j] = A[i][j]
            else:
                C[i][j] = B[i][j - len(A[0])]

    return C

def Pivot(A:list, B:list) -> list:
    # Echelonne et donne les solutions du système

    # DESCENTE
    M = MatriceAugmente(A,B)

    for k in range (0, len(M)):
        repeat  = True
        i = k
        while repeat:
            if (M[i,k] != 0):
                repeat = False
            else:
                i += 1
        
        EchangeLigne(M, i, k)

        for l in range (k+1, len(M)):
            f = M[l,k] / M[k,k]

            SousLigne(M, k, l, f)

    return M


A = np.array([
    [1,2,3],
    [1,4,9],
    [1,8,27]])

B = np.array([
    [5],
    [15],
    [47]])


print(Pivot(A,B))



[[ 1  2  3  5]
 [ 0  2  6 10]
 [ 0  0  6 12]]


In [307]:
def remonte(M): #INCOMPLET
    for k in range (0, len(M)):
        for l in range (k, len(M)):
            print(M[-l,-k-1], M[-k,-k-1])
            f = M[-l,-k-1] / M[-k,-k-1]
            SousLigne(M, -k, -l, f)