# TP n°2

### Félix Ladislas & Maxime Lenfant

Date de la séance : 28/09/2023

___

In [7]:
import numpy as np

___
## Préliminaires

In [8]:
L1 = np.array([1,2,3,4]) ; L2 = L1
L1[1] = 0 ; print(L2)

[1 0 3 4]


On crée un tableau *L1*, puis on déclare un second tableau *L2* égal au premier. Pour finir, on change la deuxième valeur de *L1* et on affiche *L2*. On remarque que le changement est aussi effectif sur le second tableau *L2*.

In [12]:
M1 = [[0]*4]*4 ; print(M1)
M1[1][2] = 5 ; print(M1)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 0, 5, 0], [0, 0, 5, 0], [0, 0, 5, 0], [0, 0, 5, 0]]


On remarque que quelque soit la valeur dans le premier chrochet de la seconde ligne, chaque élément du tableau *M1* change de manière identique.

In [10]:
M1 = np.array([[0]*4]*4)
M1[1][2] = 5 ; print(M1)

[[0 0 0 0]
 [0 0 5 0]
 [0 0 0 0]
 [0 0 0 0]]


Ici, grâce à la déclarationi et initialisation par *numpy*, le changement se fait bien dans un seul élément de *M1*.

In [19]:
A = np.array([[1,2,3],[1,4,9],[1,8,27]])
AA = A ; AA[1,1] = -2 ; A

array([[ 1,  2,  3],
       [ 1, -2,  9],
       [ 1,  8, 27]])

De manière similaire à la première question, le changement effectué sur le tableau *AA* s'effectue aussi sur le tableau *A* dont il est l'origine.

In [20]:
A = np.array([[1,2,3],[1,4,9],[1,8,27]])
AA = A.copy() ; AA[1,1] = -2 ; A

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

Ici, la fonction *copy()* permet de copier un tableau. Un changement sur l'un n'affecte plus l'autre.

___