# TP n°3

### Félix Ladislas & Maxime Lenfant

Date de la séance : 12/10/2023

___

In [91]:
import numpy as np

___
## Préliminaires

In [92]:
L1 = np.array([1,2,3,4]) ; L2 = L1
L1[1] = 0 ; print(L2)

[1 0 3 4]


On crée un tableau *L1*, puis on déclare un second tableau *L2* égal au premier. Pour finir, on change la deuxième valeur de *L1* et on affiche *L2*. On remarque que le changement est aussi effectif sur le second tableau *L2*.

In [93]:
M1 = [[0]*4]*4 ; print(M1)
M1[1][2] = 5 ; print(M1)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 0, 5, 0], [0, 0, 5, 0], [0, 0, 5, 0], [0, 0, 5, 0]]


On remarque que quelque soit la valeur dans le premier chrochet de la seconde ligne, chaque élément du tableau *M1* change de manière identique.

In [94]:
M1 = np.array([[0]*4]*4)
M1[1][2] = 5 ; print(M1)

[[0 0 0 0]
 [0 0 5 0]
 [0 0 0 0]
 [0 0 0 0]]


Ici, grâce à la déclarationi et initialisation par *numpy*, le changement se fait bien dans un seul élément de *M1*.

In [95]:
A = np.array([[1,2,3],[1,4,9],[1,8,27]])
AA = A ; AA[1,1] = -2 ; A

array([[ 1,  2,  3],
       [ 1, -2,  9],
       [ 1,  8, 27]])

De manière similaire à la première question, le changement effectué sur le tableau *AA* s'effectue aussi sur le tableau *A* dont il est l'origine.

In [96]:
A = np.array([[1,2,3],[1,4,9],[1,8,27]])
AA = A.copy() ; AA[1,1] = -2 ; A

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

Ici, la fonction *copy()* permet de copier un tableau. Un changement sur l'un n'affecte plus l'autre.

___

# Algorithme TP°2

In [97]:
def SousLigne(M:list,L1:int,L2:int, f:float):
    # Soustrait la ligne L1 à la ligne L2 de la matrice M :
    # (L2 = L2 - f * L1)

    for i in range (0,len(M[L2])):
        M[L2][i] = M[L2][i] - (f * M[L1][i])

def EchangeLigne(M:list,L1:int,L2:int):
    # Echange L1 et L2 dans le tableau M

    M[L1], M[L2] = M[L2].copy(), M[L1].copy()

def MatriceAugmente(A:list, B:list)->list:
    # retourne la matrice augmentée A|B

    C = np.zeros([len(A), len(A[0]) + len(B[0])], int)
    
    for i in range (0, len(A)):
        for j in range (0, len(C[0])):
            if (j < len(A[0])):
                C[i][j] = A[i][j]
            else:
                C[i][j] = B[i][j - len(A[0])]

    return C

def DivLigne(M:list,L:int, f:float):
    # Divise la ligne L de la matrice M par f

    for i in range (0, len(M[L])):
        M[L][i] = M[L][i] / f

def Pivot(A:list, B:list) -> list:
    # Echelonne et donne les solutions du système

    # DESCENTE
    M = MatriceAugmente(A,B)

    for k in range (0, len(M)):
        repeat  = True
        i = k
        while repeat:
            if (M[i,k] != 0):
                repeat = False
            else:
                i += 1
        
        EchangeLigne(M, i, k)

        for l in range (k+1, len(M)):
            f = M[l,k] / M[k,k]

            SousLigne(M, k, l, f)

    # REMONTEE
    k = len(M) -1
    while k != -1:     
        l = k -1
        while l != -1:
            f = M[l,k] / M[k,k]
            SousLigne(M, k, l, f)
            l -= 1
        
        k -= 1

    for i in range (0,len(M)):
        DivLigne(M, i, M[i][i])

    return M


A = np.array([
    [1,2,3],
    [1,4,9],
    [1,8,27]])

B = np.array([
    [5],
    [15],
    [47]])

print(Pivot(A,B))

[[ 1  0  0  1]
 [ 0  1  0 -1]
 [ 0  0  1  2]]


___
# Algorithme TP°3

In [98]:
E = 10**(-20)

A = np.array([
    [E,1],
    [1,1]])

B = np.array([
    [1],
    [2]])

print(Pivot(A,B))

[[1 0 1]
 [0 1 1]]


# Question 4

In [101]:
#creer une fonction qui renvoie des matrices de taille n
#verifier l'inversibilité 
#calculer le temps machine pour la matrice
#mettre le temps et la taille dans un tableau
#faire une moyenne des temps et ratio temps/n pour voir si c'est proportionnel
from random import randint, uniform
import time

def rand_matrice(n:int, M):
    for i in range(n):
        for j in range(n):
            if i==j:
                M[i][j]=round(uniform(0.1,10.0), 2)
            else:
                M[i][j]=round(uniform(0.0,10.0), 2)
    
    
B=np.array([[1],[2],[3]])

def test(M,B,n:int):
    try :
        t=time.perf_counter()
        Pivot(M,B)
        t=time.perf_counter()-t
    except ZeroDivisionError:
        print("FF")
        return None
    finally:
        return t

def Prog(rep:int,B):
    valeurs=[]
    while rep!=0:  
        n=randint(2,10)
        M=np.zeros((n,n),float)
        rand_matrice(n,M)
        t=test(M,B,n)
        if t!=None:
            valeurs.append((t,n))
        rep-=1
    return valeurs

Prog(200,B)
def moyenne(nb:int):
    valeurs=Prog(nb,B)
    

[[2.55 2.78]
 [9.29 7.66]]
[[4.28 4.48 7.08 0.57 7.98 0.07 2.81 9.34]
 [5.74 5.02 9.45 7.16 4.39 8.02 6.05 6.75]
 [1.34 0.61 3.12 6.29 2.07 7.43 3.14 4.96]
 [5.41 8.45 5.52 4.81 9.81 1.05 8.53 0.77]
 [4.84 0.93 0.82 4.67 4.68 4.25 1.24 1.28]
 [5.21 9.65 4.31 5.96 0.68 2.91 2.55 7.14]
 [5.79 5.1  2.81 9.45 8.18 8.32 4.83 1.45]
 [3.89 3.98 4.48 7.74 5.59 9.76 6.24 5.85]]
[[8.   5.93 6.61 5.52 4.24 1.46 8.03 9.06 2.62 6.36]
 [3.82 0.78 2.07 3.75 9.85 6.25 6.74 4.97 6.51 7.45]
 [2.74 3.65 4.44 6.34 0.55 2.01 1.73 4.03 9.94 4.21]
 [9.82 7.65 3.26 7.02 8.37 2.77 4.71 4.32 1.21 1.93]
 [0.33 6.63 2.17 6.21 0.88 3.98 3.85 9.6  8.95 6.35]
 [7.54 9.49 1.77 6.82 3.45 5.9  2.97 4.69 7.68 4.36]
 [1.78 7.49 1.23 0.56 5.93 1.15 4.46 1.16 8.62 2.35]
 [0.46 8.06 8.24 6.1  4.96 7.95 7.52 7.53 9.05 2.96]
 [3.78 7.37 0.65 5.83 1.38 0.12 6.13 9.92 9.06 4.94]
 [8.76 4.91 4.26 9.74 9.2  3.83 9.   5.   5.68 5.5 ]]
[[9.51 6.48 9.9  8.72 2.68]
 [1.34 1.31 5.92 1.52 0.47]
 [5.08 1.09 9.74 9.1  9.18]
 [7.45 8.89 1

[[3.25 1.6  0.33 6.55 4.26 6.68 1.25 9.01 6.59]
 [8.85 0.33 9.66 8.57 7.68 4.75 5.65 2.01 5.67]
 [9.92 9.15 5.92 1.41 5.9  2.18 6.04 9.6  8.11]
 [3.79 5.58 1.41 3.06 3.47 3.48 7.14 2.58 3.32]
 [0.06 5.81 4.83 1.45 0.31 5.57 9.11 8.56 3.78]
 [6.64 9.31 6.48 8.25 3.25 3.48 0.51 2.4  2.47]
 [0.43 2.84 0.04 2.48 2.87 3.74 8.55 2.66 5.79]
 [8.03 6.41 2.37 3.81 1.24 3.2  6.43 3.57 2.55]
 [0.81 9.09 6.97 7.44 4.25 9.62 8.35 5.26 2.34]]
[[7.46 5.18 6.31 8.31 5.08 0.76 8.29 7.27 5.43]
 [4.13 5.96 0.03 7.22 1.8  8.88 3.05 1.34 0.02]
 [9.82 1.06 3.37 7.7  7.81 9.24 7.98 5.64 3.84]
 [9.64 1.06 2.42 5.08 8.5  4.79 5.45 9.42 1.95]
 [2.95 5.57 3.22 0.6  7.86 6.27 7.81 8.7  9.62]
 [2.94 4.11 1.64 2.16 7.49 9.35 4.13 1.2  6.37]
 [1.08 0.63 0.88 8.33 6.63 8.87 7.42 1.12 4.52]
 [8.14 7.84 2.03 7.36 1.7  5.42 6.26 2.31 3.87]
 [8.62 4.35 4.61 4.01 4.16 1.03 6.19 0.02 5.34]]
[[0.67 8.94 1.01 5.78 0.77 8.34 6.38 1.04 3.5  5.95]
 [7.72 8.43 8.65 3.22 4.46 2.03 7.34 3.49 2.65 7.26]
 [8.54 9.28 1.17 3.64 3.29 1